Models/ErrorViewModel.cs
namespace Link_Estudo.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Estudo.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Link_Estudo.Models
{
    [Table("LinkEstudo")]
    public class Estudo
    {
        [Display(Name = "Código")]
        [Column("Id")]
        public int Id { get; set; }

        [Display(Name = "Link")]
        [Column("Link")]
        public string? Link { get; set; }

        [Display(Name = "Assunto")]
        [Column("Assunto")]
        public string? Assunto { get; set; }

        [Display(Name = "Descrição")]
        [Column("Descrição")]
        public string? Descricao { get; set; }
    }
}

Controllers/EstudoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Link_Estudo.Data;
using Link_Estudo.Models;

namespace Link_Estudo.Controllers
{
    public class EstudoesController : Controller
    {
        private readonly Contexto _context;

        public EstudoesController(Contexto context)
        {
            _context = context;
        }

        // GET: Estudoes
        public async Task<IActionResult> Index()
        {
              return _context.Estudo != null ? 
                          View(await _context.Estudo.ToListAsync()) :
                          Problem("Entity set 'Contexto.Estudo'  is null.");
        }

        // GET: Estudoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Estudo == null)
            {
                return NotFound();
            }

            var estudo = await _context.Estudo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudo == null)
            {
                return NotFound();
            }

            return View(estudo);
        }

        // GET: Estudoes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Estudoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Link,Assunto,Descricao")] Estudo estudo)
        {
            if (ModelState.IsValid)
            {
                _context.Add(estudo);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(estudo);
        }

        // GET: Estudoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Estudo == null)
            {
                return NotFound();
            }

            var estudo = await _context.Estudo.FindAsync(id);
            if (estudo == null)
            {
                return NotFound();
            }
            return View(estudo);
        }

        // POST: Estudoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Link,Assunto,Descricao")] Estudo estudo)
        {
            if (id != estudo.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(estudo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EstudoExists(estudo.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(estudo);
        }

        // GET: Estudoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Estudo == null)
            {
                return NotFound();
            }

            var estudo = await _context.Estudo
                .FirstOrDefaultAsync(m => m.Id == id);
            if (estudo == null)
            {
                return NotFound();
            }

            return View(estudo);
        }

        // POST: Estudoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Estudo == null)
            {
                return Problem("Entity set 'Contexto.Estudo'  is null.");
            }
            var estudo = await _context.Estudo.FindAsync(id);
            if (estudo != null)
            {
                _context.Estudo.Remove(estudo);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool EstudoExists(int id)
        {
          return (_context.Estudo?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/HomeController.cs
using Link_Estudo.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Link_Estudo.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Estudoes - Cópia/Create.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Estudo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assunto" class="control-label"></label>
                <input asp-for="Assunto" class="form-control" />
                <span asp-validation-for="Assunto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudoes - Cópia/Delete.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Estudo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assunto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assunto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Views/Estudoes - Cópia/Details.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Estudo</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assunto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assunto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Views/Estudoes - Cópia/Edit.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Estudo</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assunto" class="control-label"></label>
                <input asp-for="Assunto" class="form-control" />
                <span asp-validation-for="Assunto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudoes - Cópia/Index.cshtml
@model IEnumerable<Link_Estudo.Models.Estudo>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assunto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Link)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assunto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Estudoes/Create.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Create";
}

<h1>Criar novas informações</h1>

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assunto" class="control-label"></label>
                <input asp-for="Assunto" class="form-control" />
                <span asp-validation-for="Assunto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-info" />
                <a asp-action="Index" class="btn btn-info">Voltar</a>
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudoes/Delete.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Delete";
}

<h3>Deseja excluir as informações?</h3>
<div>

    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assunto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assunto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Excluir" class="btn btn-info"/> 
        <a asp-action="Index" class="btn btn-info">Voltar</a>
    </form>
</div>

Views/Estudoes/Details.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Details";
}

<h1>Detalhes das informações</h1>

<div>
   
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Link)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Link)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Assunto)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Assunto)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Descricao)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Descricao)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Index" class="btn btn-info">Voltar</a>
</div>

Views/Estudoes/Edit.cshtml
@model Link_Estudo.Models.Estudo

@{
    ViewData["Title"] = "Edit";
}

<h1>Editar informações</h1>


<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Link" class="control-label"></label>
                <input asp-for="Link" class="form-control" />
                <span asp-validation-for="Link" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Assunto" class="control-label"></label>
                <input asp-for="Assunto" class="form-control" />
                <span asp-validation-for="Assunto" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div><br />
            <div class="form-group">
                <input type="submit" value="Atualizar" class="btn btn-info" />
                <a asp-action="Index" class="btn btn-info">Voltar</a>
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Views/Estudoes/Index.cshtml
@model IEnumerable<Link_Estudo.Models.Estudo>

@{
    ViewData["Title"] = "Index";
}
<h1 class="text-center">Lista de informações</h1>
<p>
    <a asp-action="Create" class="btn btn-info">Criar novas informações</a>
</p>
<hr />
<table class="table table-dark table-hover" id="dataTable">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Link)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Assunto)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descricao)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
             <td>
                    <div class="d-inline-block text-truncate" style="max-width: 400px;">
                        @Html.DisplayFor(modelItem => item.Link)
                 </div>
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Assunto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Descricao)
            </td>

            <td>
                    <div class="d-grid gap-1 col-9 mx-auto">
                    <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-info">Ver</a>
                    <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info">Editar</a>
                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-info">Excluir</a>
                    </div>
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem-Vindo</h1>
    <p>Conhecer outros projetos <a href="https://luizmarcelolm.github.io/Portfolio/">Meu Portfólio</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Link_Estudo</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Link_Estudo.styles.css" asp-append-version="true" />
      <link href="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Link_Estudo</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Meu Portfólio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Estudoes" asp-action="Index">Link para Estudo</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            Desenvolvedor asp.net mvc - Luiz Marcelo Mota <a asp-area="" asp-controller="Home" asp-action="Home">Portfólio</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
     <script src="https://cdn.datatables.net/v/dt/dt-1.13.6/datatables.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>